### ISSUE TITLE
User Digest Form

### ISSUE THREAD

**Issue by Mike-Heneghan** [Mike-Heneghan/ALISS#1]
Create a form that allows user to add a postcode(s) w/ categories - e.g. digest for postcode "EH4 4EB", categories "Money", "Health"

Create a digest page where they can see all the postcode + categories they've setup

For each postcode in page display listing of the latest 3 services updated in each of their saved categories

On same page show any "Saved services" that have been updated in the last week

**Comment by Mike-Heneghan** [comment]
- [ ] Add the JS Categories Dropdown to the Digest Form page.
- [ ] Use the form data to create new DB records.

**Comment by Mike-Heneghan** [comment]
- Add the auto-generated email methods. 
  - One builds and the second sends. 
- Add the category to the hidden field when form fails validation. 
- On fails dynamically default the drop down (edit js low-priority). 
- Front clean up the digests page with <li> and updated on.

**Comment by Mike-Heneghan** [comment]
Using the ```datetime.strp(date_string, format)``` couldn't successful convert the string with the timezone. ```format = '%Y-%m-%dT%H:%M:%S.%f%z'``` would not work and neither would ```format = '%Y-%m-%dT%H:%M:%S.%f+%z'```. When note using the timezone directive %z the leftover +00:00 was causing errors.

To overcome this it was necessary to remove the +00:00 from the string and add the timezone to the datetime object after conversion.

```
@register.filter
def format_time_string(value):
    utc = pytz.UTC
    value = value.split('+')
    value = value[0]
    d = datetime.strptime(value, '%Y-%m-%dT%H:%M:%S.%f')
    utc.localize(d)
    return d
```

**Comment by Mike-Heneghan** [comment]
Successfully Created Basic Digest Email:
<img width="917" alt="basic_digest_email" src="https://user-images.githubusercontent.com/36415632/46092370-a31e2e80-c1ac-11e8-8138-39c5d19ceeea.png">

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/46207365-0f20a400-c31f-11e8-9dbe-c3eae6407557.png)
The ```account_list``` css class has a minimum height of 600px hence the empty box. It would be good to create own although not entirely sure how in this project.

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/46207979-18ab0b80-c321-11e8-8d66-4a5c0eb0c9b6.png)

**Comment by digitalWestie** [comment]
Move deliver behaviour script:

`./manage.py shell < deliver_digest_emails.py`
