### ISSUE TITLE
Better Sign up success page content

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#10]
Add:

- Add an organisation button
- Add a service (expands to show text below)
  - You will first need to `add the organisation` that provides service
- Start a new search
- Back to my last search (dependent on the last search feature)

**Comment by Mike-Heneghan** [comment]
Added basic links with the above functionality bar message for adding the organisation.

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/47168855-e6764380-d2f9-11e8-9680-8d6469cbc49d.png)

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/47169575-d3fd0980-d2fb-11e8-9c8e-63a7bfde5e9d.png)

When the user selects "Add a Service" the information message below becomes visible with a link to add organisation.

**Comment by Mike-Heneghan** [comment]
Inadvertently broke the toggle for get started although in some ways the formatting looks better and removes the need for the click to see what to do next.

![image](https://user-images.githubusercontent.com/36415632/47170759-bed5aa00-d2fe-11e8-8eb1-7e5418416ff3.png)

**Comment by Mike-Heneghan** [comment]
Merged
