### ISSUE TITLE
Improve language  on filters 

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#102]
Under sort method we have - 
- By best match
- By nearest first
- By best keyword match

To clarify, we should change "By best keyword match" to "By keyword match". 

As "best match" is a little vague, we should add a question mark icon with tooltip saying "This is a combination of nearest first and keyword match"

**Comment by digitalWestie** [comment]
Existing tooltip code can be found in the service / organisation form templates

**Comment by Mike-Heneghan** [comment]
Merged into master
