### ISSUE TITLE
"Your last search" link in account

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#11]
You last searched: EH21 6UW, Money, for "Debt" (link)

**Comment by digitalWestie** [comment]
e.g. https://stackoverflow.com/questions/19491336/get-url-parameter-jquery-or-how-to-get-query-string-values-in-js

**Comment by Mike-Heneghan** [comment]
Wireframe: 
![image](https://user-images.githubusercontent.com/36415632/46287829-b8fc6c80-c57b-11e8-9b1a-6f1db52c5506.png)

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/47028378-38d02c80-d161-11e8-866f-9b05294cfc3f.png)

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/47033070-d16baa00-d16b-11e8-85c6-9d31adc02836.png)


Made progress although currently setup to work with postcode, category and query. Need to generate string based on which parameters are returned.

**Comment by Mike-Heneghan** [comment]
Formatting the last search string with the formula of "Postcode" + " and Category " + " for Keyword" as all searches are dependent of a postcode that will always be available although the other two are added when not null in the same order of " and Category" with " for Keyword" as seen below: 

<img width="497" alt="screen shot 2018-10-17 at 09 05 48" src="https://user-images.githubusercontent.com/36415632/47071671-0881a000-d1ec-11e8-9da8-109e421d1cf0.png">

<img width="555" alt="screen shot 2018-10-17 at 09 05 16" src="https://user-images.githubusercontent.com/36415632/47071684-0f101780-d1ec-11e8-8811-94ab3d0a71a0.png">

<img width="519" alt="screen shot 2018-10-17 at 09 06 17" src="https://user-images.githubusercontent.com/36415632/47071698-19321600-d1ec-11e8-8923-79a4660f8a03.png">

<img width="613" alt="screen shot 2018-10-17 at 09 04 47" src="https://user-images.githubusercontent.com/36415632/47071716-218a5100-d1ec-11e8-829e-bff765869722.png">

**Comment by Mike-Heneghan** [comment]
Currently keeping with the blue/green text colour for links and could capitalise all terms in category and query if desired.

**Comment by Mike-Heneghan** [comment]
Added "" around Category and Keyword to improve readibility? 

![image](https://user-images.githubusercontent.com/36415632/47079512-9fa32380-d1fd-11e8-96c5-c2c17b270c01.png)

At the moment the keyword search doesn't remove special characters although I don't think this will be an issue.

**Comment by Mike-Heneghan** [comment]
Also as seen above the code can't handle categories where & are used instead of "and". As the slug which is in the url uses - and doesn't differentiate where the & should go.

**Comment by Mike-Heneghan** [comment]
Merged
