### ISSUE TITLE
Change colour of more locations in search results

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#12]
(use yellowy-orange we already have elsewhere)

**Comment by Mike-Heneghan** [comment]
Colour: #f49c27

**Comment by digitalWestie** [comment]
It should be defined as a variable somewhere, so if you can stick to that our stylesheets will be easier to maintain.

**Comment by Mike-Heneghan** [comment]
Updated my forks master and checked out a branch for the enhancement ```enhance/locations-colour```. 

- [ ] Find the colour to use (Colour: #f49c27)
- [ ] Find the variable in the stylesheets.
- [ ] Update with the new colour.
- [ ] Visually check front-end to ensure it has worked as intended

**Comment by Mike-Heneghan** [comment]
<a class="more-link">More Locations</a>

Bit of trouble generating the static files from the scss files using gulp although completed now. 

Edited the ```src/scss/partials/results.scss``` file to overwrite the colour to #f49c27.

**Comment by Mike-Heneghan** [comment]
Manually merged
