### ISSUE TITLE
Refactor digests out of views/accounts.py and into its own file

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#23]
We have some huge files in this project, it would be nice to re-organise some stuff.

**Comment by Mike-Heneghan** [comment]
To move the files across from accounts: 

- [ ] Move the methods across from the `account.py` view files to a `digest.py` file.
- [ ] Ensure the imports are in place.
- [ ] Edit the digest view method names to remove the account reference.
- [ ] Update the `account.py` urls file to update the view imports.

**Comment by Mike-Heneghan** [comment]
Merged into master
