### ISSUE TITLE
Change language of 'digests' to 'notifications'

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#24]
E.g. my digests will be come a general 'my notifications' page

This is also future proofing in that the current `my_digest.html` page will be where the user can manage their email settings.

Page title 'My digest' -> 'My notifications' 

Then add a sub-heading of 'New services', with the "Keep me up to date with new services..." text.

**Comment by Mike-Heneghan** [comment]
Going to build on the work from: https://github.com/Mike-Heneghan/ALISS/issues/25
