### ISSUE TITLE
Change behaviour of digest to only update on discovery of new services

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#25]
ALISS team preferred to just find out about new stuff.

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/49937290-2e66b080-fece-11e8-92ed-e1179c9cad14.png)

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/49937328-50603300-fece-11e8-8766-dc38af9fbbe1.png)

**Comment by Mike-Heneghan** [comment]
The digest now uses `retrieve_new_services` which returns the services with a `created_on` which is later than the comparison date. Also updated the language in the template and email to reflect the change.
