### ISSUE TITLE
Implement an organisation mapping, and search function in search.py

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#26]
Should be much more basic than searching a service is now. Only need to search against name & description.

Results returned should have id, name, description, published status.

Later this will be used in the first step in 'add an organisation'.

Start by adding a mapping, following example of service, e.g. in `search_tasks.py`: 

```
'mappings': {
                'service': {
                    'properties': service_mapping
                }
            },
```

**Comment by digitalWestie** [comment]
NB- you'll need to extend index_all() in search_tasks.py to cover indexing of organisations.

**Comment by Mike-Heneghan** [comment]
- [ ] Updated search.py with Organisation
- [ ] Update search_tasks.py mapping

**Comment by Mike-Heneghan** [comment]
![image](https://user-images.githubusercontent.com/36415632/49952981-0dfe1c80-fef5-11e8-9fa9-8d2e57161aa6.png)

**Comment by Mike-Heneghan** [comment]
## Search Organisations in the shell

```
from aliss.search import *
from elasticsearch_dsl import Search
from elasticsearch_dsl.connections import connections

connections.create_connection(
  hosts=[settings.ELASTICSEARCH_URL], timeout=20, http_auth=(settings.ELASTICSEARCH_USERNAME, settings.ELASTICSEARCH_PASSWORD)
)

queryset = Search(index='organisation_search', doc_type='organisation')
s = filter_organisation_by_query(queryset, "shed")
s.execute()
```

**Comment by Mike-Heneghan** [comment]
```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from aliss.search import *
>>> from elasticsearch_dsl import Search
>>> from elasticsearch_dsl.connections import connections
>>>
>>> connections.create_connection(
...   hosts=[settings.ELASTICSEARCH_URL], timeout=20, http_auth=(settings.ELASTICSEARCH_USERNAME, settings.ELASTICSEARCH_PASSWORD)
... )
<Elasticsearch([{'host': 'localhost', 'port': 9200, 'scheme': 'http'}])>
>>>
>>> queryset = Search(index='organisation_search', doc_type='organisation')
>>> s = filter_organisation_by_query(queryset, "shed")
>>> s.execute()
<Response: [<Hit(organisation_search/organisation/6d46b68a-4f36-4d0b-b3e4-200af1a352e1): {'id': '6d46b68a-4f36-4d0b-b3e4-200af1a352e1', 'name': 'Scot...}>]>
>>> res = s.execute()
>>> res[0]
<Hit(organisation_search/organisation/6d46b68a-4f36-4d0b-b3e4-200af1a352e1): {'id': '6d46b68a-4f36-4d0b-b3e4-200af1a352e1', 'name': 'Scot...}>
>>> res[0].name
'Scottish Men’s Shed Association'
>>> res[0].id
'6d46b68a-4f36-4d0b-b3e4-200af1a352e1'
>>> res[0].description
'The Scottish Men’s Shed Association was launched in November 2015 with the aim of helping new and existing groups to set up and run a Men’s Shed in their local town or community. We are here to give a helping hand to anyone looking for assistance or more information on what it means to develop and run a Men’s Shed.'
>>> res[0].published
True
```

**Comment by Mike-Heneghan** [comment]
`organisation_search` index can be searched although queryset has to be defined. I'm sure we'll fnd out the ramifications of this as we try to implement it.

**Comment by Mike-Heneghan** [comment]
When we want to implement the organisation_seach we'll need to define the queryset in the same way we've been doing for the `search` index as per digest code:

```
def retrieve(self, comparison_date):

        # Create connection to elastic search
        connections.create_connection(
            hosts=[settings.ELASTICSEARCH_URL], timeout=20, http_auth=(settings.ELASTICSEARCH_USERNAME, settings.ELASTICSEARCH_PASSWORD))

        queryset = Search(index='search', doc_type='service')
        queryset = filter_by_postcode(queryset, self.postcode)
        if (self.category):
            queryset = filter_by_category(queryset, self.category)
        queryset = queryset.sort({ "last_edited" : {"order" : "desc"}})
        comparison_date_string = comparison_date.strftime("%Y-%m-%d"'T'"%H:%M:%S")
        queryset = filter_by_last_edited(queryset, comparison_date_string)

        return queryset.execute()
```

**Comment by Mike-Heneghan** [comment]
As a means of testing need to add the elastic search for an organisation by id and the filter organisation by a query to the Organisation model and test. 

- [ ] Add `get_organisation_by_id` to the model.
- [ ] Test 
- [ ] Add `filter_organisation_by_query` to the model.
- [ ] Test

Will also need to make sure that the elastic search index for organisations is kept updated with changes in the db in a similar way to service.

- [ ] Add check updating `organisation_search` index on `save()`

**Comment by Mike-Heneghan** [comment]
Update the organisation search view to use the elastic_search version.

**Comment by Mike-Heneghan** [comment]
To allow the organisations to be ordered by `created_on` had to be added to the service mapping.

**Comment by Mike-Heneghan** [comment]
To allow the claimed info to be available to users need to add it to the elastic search mapping.

- [ ] Add

**Comment by Mike-Heneghan** [comment]
Need to add the logic for the keyword search into the view:

- [ ] Access the keyword in the view.
- [ ] Use the keyword for the elastic search filter.

**Comment by Mike-Heneghan** [comment]
Need to test the view to make sure that the account privileges work is taken into account with the different results of an organisation search. 

- [ ] Test that user gets published and unpublished results when they are staff.
- [ ] Test that the basic user only gets the published results.

**Comment by Mike-Heneghan** [comment]
Need to check the pagination for the elastic search results. Also noted that the elastic search query is more selective about results. For example, an Organisation called First Testing Org would not be returned with the query "test".

**Comment by Mike-Heneghan** [comment]
Organisation Mapping Search Next Steps:

- [ ] Port over the elastic search optimisations to organisation_search mapping.

**Comment by Mike-Heneghan** [comment]
Merged into master.
