### ISSUE TITLE
Move deliver behaviour into script

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#3]
so we can tell cron job:  `python manage.py shell < deliver_digest_emails.py`

Current setup: `heroku local:run python3 manage.py deliver_digest_emails`

**Comment by Mike-Heneghan** [comment]
Need to edit the send_digest_email so that it takes the user as a parameter. The write code to iterate through all users and send their digest selections.

**Comment by Mike-Heneghan** [comment]
Some advice to set this up as a custom command in a similar fashion to import postcodes.

https://stackoverflow.com/questions/16853649/how-to-execute-a-python-script-from-the-django-shell

**Comment by Mike-Heneghan** [comment]
The only issue could be that in the current state of the deliver_digest_emails custom command needs the elastic search to be connected already. 

Maybe this is already being down and doesn't need to be incorporated.

**Comment by Mike-Heneghan** [comment]
Holding off on a pull request as currently there are more things to check and potentially add such as better formatted email.

**Comment by Mike-Heneghan** [comment]
Merged
