### ISSUE TITLE
Re-style organisation results on 'add an organisation' page to a table view

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#30]
Two columns, just name and actions. See 'my-organisations' for an example.

**Comment by Mike-Heneghan** [comment]
View to be updated:

![image](https://user-images.githubusercontent.com/36415632/51855412-1d122000-2325-11e9-914d-2d7718fe6333.png)

Guide: 

![image](https://user-images.githubusercontent.com/36415632/51855295-cdcbef80-2324-11e9-9688-6e87ac281011.png)

**Comment by Mike-Heneghan** [comment]
Refactored the add organisation page to show results as a table. It appears to be working with no issues and performing as expected in line with the my-organisations page. 

![image](https://user-images.githubusercontent.com/36415632/51900015-2397aa80-23ac-11e9-8cc6-e975be305aff.png)

**Comment by Mike-Heneghan** [comment]
Merged into master
