### ISSUE TITLE
Organisation search view and template

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#32]
- name
- description (partial if too long)
- website
- number
- note any other ideas for content, sorting, filtering, whatever

**Comment by Mike-Heneghan** [comment]
Had a look for some inspiration of potential solutions online:

<img width="975" alt="screenshot 2019-01-29 at 10 32 16" src="https://user-images.githubusercontent.com/36415632/51903435-0cf55180-23b4-11e9-8954-0e8ba6042006.png">

<img width="975" alt="screenshot 2019-01-29 at 10 32 27" src="https://user-images.githubusercontent.com/36415632/51903446-14b4f600-23b4-11e9-97f9-635937475131.png">

<img width="1404" alt="screenshot 2019-01-29 at 10 32 39" src="https://user-images.githubusercontent.com/36415632/51903455-1aaad700-23b4-11e9-9634-139f95dcbe60.png">

<img width="1404" alt="screenshot 2019-01-29 at 10 32 49" src="https://user-images.githubusercontent.com/36415632/51903463-23031200-23b4-11e9-8c49-d773b4115d17.png">

**Comment by Mike-Heneghan** [comment]
In some respects the https://www.gov.uk/search site with a simple clean search bar doesn't distract the user from the intended task. In some ways having a search that could handle whether it was a postcode or keyword and return the results accordingly would be best although could be overly challenging at this stage.

The NHS https://www.nhs.uk/service-search search has quite a lot of content and adding the extra search box I suspect wouldn't be in the interest of most users. 

In a similar case for the https://www.search.co.uk/ site the extra box I don't think wouldadd value for most users. 


The https://statistics.gov.scot/home site uses tabs which could be a useful solution for us. They would avoid being overly distracting and the orgsanisations tab could be found by those who needed it.

**Comment by Mike-Heneghan** [comment]
Potentially a search box with tabs could be a good solution. 

<img width="833" alt="screenshot 2019-01-29 at 11 29 17" src="https://user-images.githubusercontent.com/36415632/51905569-76c42a00-23b9-11e9-8a6d-29f9497f1639.png">

**Comment by Mike-Heneghan** [comment]
Focussing on adding the view itself based on the service search results and not worrying about the ui for how to start the search and get there.

**Comment by Mike-Heneghan** [comment]
To get to the Organisation Search results view url: //localhost:5000/search/organisations/

**Comment by Mike-Heneghan** [comment]
For development added a search box which takes keywords to search the organisation_search index.

<img width="833" alt="screenshot 2019-01-29 at 16 10 21" src="https://user-images.githubusercontent.com/36415632/51922178-6ecbb080-23e0-11e9-8cd5-8ec2c98170cc.png">

**Comment by Mike-Heneghan** [comment]
Created a basic results page with poor formatting:

<img width="1142" alt="screenshot 2019-01-29 at 16 12 31" src="https://user-images.githubusercontent.com/36415632/51922323-b6523c80-23e0-11e9-9203-60de663df21c.png">

**Comment by Mike-Heneghan** [comment]
Need to add content to the organisation_mapping for the results of the search. Potentially useful information for those searching organisations:

- [ ] Website 
- [ ] Telephone Number
- [ ] Locations

**Comment by digitalWestie** [comment]
Looking great so far. One pedantic ALISS style guide thing though, apart from the main big heading, stick to a single capitalised letter e.g. 'New search' instead of 'New Search'

**Comment by digitalWestie** [comment]
Also, no ampersands, just use 'and'.

**Comment by Mike-Heneghan** [comment]
> Looking great so far. One pedantic ALISS style guide thing though, apart from the main big heading, stick to a single capitalised letter e.g. 'New search' instead of 'New Search'

<img width="1142" alt="screenshot 2019-01-29 at 16 27 59" src="https://user-images.githubusercontent.com/36415632/51923450-e8fd3480-23e2-11e9-8464-b765896ec6ab.png">

**Comment by Mike-Heneghan** [comment]
Added further information to the results of the organisation search:

<img width="1179" alt="screenshot 2019-01-30 at 11 44 20" src="https://user-images.githubusercontent.com/36415632/51979306-b73caa00-2484-11e9-9796-c8b9bf2a57ab.png">

**Comment by Mike-Heneghan** [comment]
As a potential idea for the sorting and filtering could sort by claimed? At the moment only published results show up for base permissions users.

**Comment by Mike-Heneghan** [comment]
Added a claim status filter for results:

<img width="1179" alt="screenshot 2019-01-30 at 14 03 38" src="https://user-images.githubusercontent.com/36415632/51986327-e6104b80-2497-11e9-9849-ba5c73399be2.png">

<img width="1179" alt="screenshot 2019-01-30 at 14 03 43" src="https://user-images.githubusercontent.com/36415632/51986334-e9a3d280-2497-11e9-9fb8-9a8f8129bee6.png">

<img width="1179" alt="screenshot 2019-01-30 at 14 03 49" src="https://user-images.githubusercontent.com/36415632/51986340-edcff000-2497-11e9-9ae5-96ebd92c7238.png">

**Comment by Mike-Heneghan** [comment]
A filter for Organisations that have services could be useful. So options for all orgs, orgs, with services and orgs without services? 

- [ ] Add radio buttons
- [ ] Create a filter for organisations with at least one service. 
- [ ] Connect filer to radio buttons.

**Comment by Mike-Heneghan** [comment]
A categories filter could be created for Organisations based on the categories the services associated with it provide?

A services_categories field could be added to the organisation_mapping which would be an array of all the associated services.

**Comment by Mike-Heneghan** [comment]
A sort by date of some kind could be useful? Potentially by last_edited?

**Comment by Mike-Heneghan** [comment]
Plan:

- [ ] Hide the filter by number of services as might be out of sync with db. (Could be found using a call to the db)
- [ ] Fix the keyword not appearing from the search page search box. 
- [ ] Change `query` to `q` in the params. 
- [ ] Refactor the urls so that general search is organisations/search and add-as-org becomes organisations/create-search.
- [ ] Refactor the OrganisationSearchView to potential-create url and the name of the class.
