### ISSUE TITLE
'Email recommendations' - if recommendations are empty, show cannot email message

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#4]
See https://github.com/aliss/ALISS/issues/12

**Comment by digitalWestie** [comment]
In Email recommendations modal say there are no services, and hide input box.

**Comment by Mike-Heneghan** [comment]
Added conditional statement to template so that if a Recommendations List has no services user is shown a message and linked to homepage to search for services. 

![image](https://user-images.githubusercontent.com/36415632/47089664-39c49500-d219-11e8-8f07-fdc5cc7972bd.png)

**Comment by Mike-Heneghan** [comment]
Merged
