### ISSUE TITLE
Support legacy urls

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#40]
These are: 

`/search/?q=&distance=10&latitude=56.73334200000001&longitude=-2.6552888999999595&location=Brechin,+United+Kingdom&page=1`

`/search/?q=&location=Erskine+PA8+7FG,+United+Kingdom&latitude=55.8907926&longitude=-4.444185400000038&distance=15`

`https://www.aliss.org/search/?q=health&accounts=179,91,268&lat=56.47347449999999&lng=-2.957288100000028&location=Dundee%20DD4%207AA,%20United%20Kingdom`

Pseudocode:

In search `get` method. Before anything happens, check if we have location param, check contents for Erskine, Dundee, Brechin, then redirect with a valid postcode variable maintaining `q`, else do nothing.

**Comment by Mike-Heneghan** [comment]
Large User central postcode in Brechin: https://checkmypostcode.uk/dd96ad#.XG6tlJP7TOQ

**Comment by Mike-Heneghan** [comment]
The current code is successfully interpreting the params when Brechin, Dundee or Erskine are within the location variable. 

Currently showing results for EH21 6UW as I don't have dummy data for postcodes associated with Brechin, Dundee or Erskine. 

Also, the code isn't very clean and there's a fair bit of repetition.

**Comment by Mike-Heneghan** [comment]
To do:

- [ ] Update to use a central postcode the three locations.
- [ ] Write tests with db results for each of the locations. 
- [ ] Try to refactor to improve the implementation.

**Comment by Mike-Heneghan** [comment]
The central postcodes I've selected are as follows:

- Brechin: DD9 6AD (https://checkmypostcode.uk/dd96ad#.XG6tlJP7TOQ)
- Erskine:  PA8 7WZ (https://checkmypostcode.uk/pa87wz)
- Dundee: DD3 8EA (https://checkmypostcode.uk/dd38ea#.XHenb1P7TUI)

Each seems to be a "large user" postcode in a central location. I'll need to add test locations and test for these as they are not available

**Comment by Mike-Heneghan** [comment]
Erskine:

PA8 7WZ | PA8 | PA8 7 | 55.9054667 | -4.45330031 | S12000038 | S08000021 | S37000024
-- | -- | -- | -- | -- | -- | -- | --

Brechin:

DD9 6AD | DD9 | DD9 6 | 56.73313937 | -2.65779541 | S12000041 | S08000027 | S37000003
-- | -- | -- | -- | -- | -- | -- | --

Dundee:

DD3 8EA | DD3 | DD3 8 | 56.47774662 | -2.98519045 | S12000042 | S08000027 | S37000007
-- | -- | -- | -- | -- | -- | -- | --

**Comment by Mike-Heneghan** [comment]
In progress of adding a service to each of the locations and checking that it returns results although that might be overkill and not add any extra value. Checking that when a legacy url is hit  it returns a 200 status code, the chosen postcode for that area and any optional queries should be sufficient.

**Comment by Mike-Heneghan** [comment]
Merged into master
