### ISSUE TITLE
How do we make ALISS more useable under keyboard only conditions?

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#41]
Questions:
- Have we got a good tab order?
- Are we able to select links, buttons, etc?
- Is it obvious when things are selected/focused?
- What best practice can we learn from other sites?

To investigate try using the site with keyboard only. Just browsing / searching actions for now.

**Comment by Mike-Heneghan** [comment]
Potential Iprovements:

- [ ] Skip to main content option as per MDN and BBC. 
<img width="366" alt="screenshot 2019-03-01 at 15 41 26" src="https://user-images.githubusercontent.com/36415632/53648720-847b0280-3c38-11e9-9eeb-43ed108f856d.png">


- [ ] Currently the "Filter by category" dropdown is skipped when tabbing through.

**Comment by Mike-Heneghan** [comment]
Useful Info:

- [ ] https://www.nngroup.com/articles/keyboard-accessibility/

**Comment by Mike-Heneghan** [comment]
For making the category select more keyboard accessible notices that even adding a `tabindex="0"` allowed the user to focus on it but hitting enter did not open dropdown.

This is not the case with the sub-categories which work as we would like. I think it could be the way the dropdown initial selection is controlled in the js.

**Comment by Mike-Heneghan** [comment]
To have the "Filter by category" operate as desired had to add a .keypress event handler in scripts.js

```
  // Cat Menu
  $(".category-selector ul > li > a.active-cat, .category-selector .cells > ul > li > a.select-category, .category-selector .cells > ul > li > span.select").click(function(e) {
    var parent = $(this).parent('li');
    parent.toggleClass('active');
  }).keypress(function(e) {
    var parent = $(this).parent('li');
    parent.toggleClass('active');
  });
```

**Comment by Mike-Heneghan** [comment]
The .keypress solution to making the enter key trigger actions allowes any key to be used for it. Not sure whether that's an issue.

**Comment by Mike-Heneghan** [comment]
Example of the bbc "Skip to content" example in dev tools: 

<img width="376" alt="screenshot 2019-03-04 at 16 03 44" src="https://user-images.githubusercontent.com/36415632/53745595-37489c00-3e97-11e9-81a3-f23e45a74fb9.png">

**Comment by Mike-Heneghan** [comment]
An example of the Skip to content from Github 
```
<a href="#start-of-content" tabindex="1" class="p-3 bg-blue text-white show-on-focus js-skip-to-content">Skip to content</a>
```

Has a positive tabindex and appears on select. Also links to href"start-of-content"

For us we need to:
- [ ] Create the link which should start hidden but when selected should become visible in a simple box. 
- [ ] Add make the box have a tabindex="1".
- [ ] Make sure we have the correct target for the href so the user is directed to the main content.

**Comment by Mike-Heneghan** [comment]
Useful information on a skip to main content function: https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/

**Comment by Mike-Heneghan** [comment]
For the `Skip to content` feature, it might be to create a partial which could take the id of the main content as a variable? For the moment I'll stick to one implementation and then have the potential to abstract it out into a partial.

**Comment by Mike-Heneghan** [comment]
Sample styling of skip to content link:
```
#skip-content {
  a.skip-content {
    left:-999px;
    position:absolute;
    top:auto;
    width:1px;
    height:1px;
    overflow:hidden;
    z-index:-999;
  }
  a.skip-content:focus, a.skip-content:active {
      color: #fff;
      background-color:#000;
      left: auto;
      top: auto;
      width: 30%;
      height: auto;
      overflow:auto;
      margin: 10px 35%;
      padding:5px;
      border-radius: 15px;
      border:4px solid yellow;
      text-align:center;
      font-size:1.2em;
      z-index:999;
  }
}
```

```
<section id="skip-content">
  <a class="skip-content" href="#content" tabindex="1">Skip to Content</a>
</section>
```

**Comment by Mike-Heneghan** [comment]
The skip to content box styling is improved but it could definitely be better.

<img width="1224" alt="screenshot 2019-03-05 at 11 32 20" src="https://user-images.githubusercontent.com/36415632/53802682-5e0bde80-3f3a-11e9-8a1a-e588edb85007.png">

- More of a space between the link and the rest of the section. 
- Formatted over to the left?

**Comment by Mike-Heneghan** [comment]
The navigation isn't tabable when collapsed as seen below:

<img width="148" alt="screenshot 2019-03-05 at 11 35 19" src="https://user-images.githubusercontent.com/36415632/53802842-c955b080-3f3a-11e9-88b7-91309e1ab74b.png">

**Comment by Mike-Heneghan** [comment]
Need to add better margin to the skip to contet link, and have it to the left.

<img width="732" alt="screenshot 2019-03-05 at 12 14 28" src="https://user-images.githubusercontent.com/36415632/53804759-3f104b00-3f40-11e9-8e22-ce0d45f9fb50.png">

**Comment by Mike-Heneghan** [comment]
To Do List:

- [ ] Add skip to content list on the homepage.

**Comment by Mike-Heneghan** [comment]
On skip to content on the homepage, the page moves down but the users have to hit tab once more for focus in the postcode search field. Might not be ideal but skipping the navigation is handy. 

It would be better to create the skip to content as a partial which takes a link to the correct section.

Also, need to test the detail pages.

**Comment by Mike-Heneghan** [comment]
Merged into master although `gulp` needs to run before the JS behaviour comes into effect.
