### ISSUE TITLE
Tooltips to help guide user when creating organisations or services

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#43]
(i) icon beside field names with description.

**Comment by Mike-Heneghan** [comment]
Example of tool tip in the project.

<img width="491" alt="screenshot 2019-02-28 at 15 17 36" src="https://user-images.githubusercontent.com/36415632/53576624-09e4b100-3b6c-11e9-845c-d0c22ff9dfc2.png">

**Comment by Mike-Heneghan** [comment]
<img width="591" alt="screenshot 2019-02-28 at 15 19 35" src="https://user-images.githubusercontent.com/36415632/53576735-47e1d500-3b6c-11e9-8bb3-656039a2b9ae.png">

**Comment by Mike-Heneghan** [comment]
Doc entry on adding help_text: https://docs.djangoproject.com/en/1.11/topics/forms/modelforms/#overriding-the-default-fields

**Comment by Mike-Heneghan** [comment]
Seems more sensible to have the help_text defined in the model form as it pertains to the model form and avoids adding verbose text to the model which is already complex. 

```
import from django.utils.translation import ugettext_lazy as _
 
    help_texts = {
            'description': _('Helpful test for a description'),
        }
```

**Comment by Mike-Heneghan** [comment]
Organisation To Do List:
 - [ ] Review the help text and make sure it's relevant.
 - [ ] ~Change the (?) to an (i)~ I think the (?) is more appropriate?

**Comment by Mike-Heneghan** [comment]
Services to Do List:

- [ ] Check whether the same method can be used for adding new services. 
- [ ] Write help_text for adding services. 
- [ ] Test and review content.

**Comment by Mike-Heneghan** [comment]
As the tooltip.html is now spread between `multiselect_field.html` and `field.html`  maybe it should be abstracted out into it's own partial?

**Comment by Mike-Heneghan** [comment]
In trying to implement the tooltip on the organisation logo field inadvertently created it with a different style. 

<img width="839" alt="screenshot 2019-03-01 at 14 08 51" src="https://user-images.githubusercontent.com/36415632/53643312-a6ba5380-3c2b-11e9-8b8d-7d55892cde3f.png">

It seems that where the tool tip (?) icon has been implemented elsewhere it's being the larger grey or red version. So for consistentency will update the Logo (?) in organisations. 

Definitely starting to feel like the knowledge is being spread to multiple places in the app so updating in thre future could be problematic.

**Comment by Mike-Heneghan** [comment]
Unfortunately the `logo-select` class in the css is interfereing with the styling of the field label and tooltip. 
```
<div class="f-row logo-select">
  <label for="id_logo">
    Logo
    {% if form.logo.help_text %}
    <span data-tooltip aria-haspopup="true" class="has-tip right" data-disable-hover="false" tabindex="2" title="{{form.logo.help_text}}">
      <i class="fa fa-question-circle" aria-hidden="true"></i>
    </span>
    {% endif %}
  </label><br/>
```
<img width="788" alt="screenshot 2019-03-01 at 14 41 34" src="https://user-images.githubusercontent.com/36415632/53645176-382bc480-3c30-11e9-9fc4-b1ae3293ee56.png">


vs.
```
<div class="f-row">
    <label for="id_logo">
      Logo
      {% if form.logo.help_text %}
      <span data-tooltip aria-haspopup="true" class="has-tip right" data-disable-hover="false" tabindex="2" title="{{form.logo.help_text}}">
        <i class="fa fa-question-circle" aria-hidden="true"></i>
      </span>
      {% endif %}
    </label><br/>
```
<img width="800" alt="screenshot 2019-03-01 at 14 37 42" src="https://user-images.githubusercontent.com/36415632/53644913-a91eac80-3c2f-11e9-9b94-d43b742224af.png">

**Comment by Mike-Heneghan** [comment]
Tried sorting this although it's becoming a bit of a palava for something which in many ways doesn't need an explanation or could be achieved through a more direct (not as good a practive approac like inline styling?).
