### ISSUE TITLE
Provide an API end-point for querying postcode by place name

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#65]
A new endpoint at `api/v4/postcodes`. Should take form of a view living in `aliss/api/v4_views.py`. 

Relevant docs: 

- API views: https://www.django-rest-framework.org/api-guide/generic-views/
- Serializing json responses: https://www.django-rest-framework.org/api-guide/serializers/

Any requests should provide a `q` param, which are used to to filter results ([`istartswith` is prob best for this](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#std:fieldlookup-startswith)).

**Comment by Mike-Heneghan** [comment]
The Postcode table has been updated to add a column with place names. 

- Need to add an endpoint for querying place names.
- Update the autocomplete code to use the endpoint rather than the hard-coded locations.
- Need to create a view which takes a query with a minimum of three letters and returns a json collection of matching names.
- Something like `/api/places/?q=Abe`

**Comment by Mike-Heneghan** [comment]
Basic view returning a dictionary of `place_names` and `postcode`.

<img width="1183" alt="Screenshot 2019-04-18 at 11 27 07" src="https://user-images.githubusercontent.com/36415632/56354935-f13c6300-61cc-11e9-917b-25ef6eb4d2f7.png">

**Comment by Mike-Heneghan** [comment]
Filtering the data set but not with proper url format?

<img width="1150" alt="Screenshot 2019-04-18 at 13 02 45" src="https://user-images.githubusercontent.com/36415632/56359734-492d9680-61da-11e9-91b7-a4df91d45397.png">

**Comment by Mike-Heneghan** [comment]
Updated the API view for post-code locations to take a query `q` and filter results which start with that.

<img width="1158" alt="Screenshot 2019-04-18 at 14 15 32" src="https://user-images.githubusercontent.com/36415632/56363569-741ce800-61e4-11e9-97b7-18996027acf9.png">

**Comment by Mike-Heneghan** [comment]
Need to now query the api for the `place_name` and `postcode` rather than using the hard coated data.

**Comment by Mike-Heneghan** [comment]
The api is now successfully returning the place_name and postcode data for the Easy-Autocomplete feature. 

https://drive.google.com/file/d/1bNRMY_1_Z83SyuRm2TldfQSrKVIyYfLj/view?usp=sharing

**Comment by Mike-Heneghan** [comment]
To do list:

- [ ] Ensure the API isn't exposed (disable CORS)?
- [ ] Write tests for the new API endpoint. 
- [ ] Send PR.

**Comment by digitalWestie** [comment]
Don't worry about API exposure for now, we can deal with it later, as team are making noises about this.

**Comment by Mike-Heneghan** [comment]
> Don't worry about API exposure for now, we can deal with it later, as team are making noises about this.

I've also been trying to write a test although currently, I'm not getting responses as I would expect. When manually testing the locations are returned as per the google drive link above. 

As this is a priority I'll send the PR and we can discuss tests and API exposure when it's convenient.

**Comment by Mike-Heneghan** [comment]
Merged into master.
