### ISSUE TITLE
Boundary geocoder

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#76]
In the following folder there's ruby code for determining the local authority a set of coordinates are found in:

https://github.com/openactive/api-dashboard/tree/master/lib/local_geocoder

It uses a ruby library called 'local-geocoder' which provides a geometry class with a `contains_point?` method.

The goal here would be to write equivalent version, but in python. It's possible someone has done this before so first step is to research code elsewhere.

This above example is fixed to UK local authorities, whereas we want to work to something a bit more abstract if possible. 

Edit- it looks like the `shapely` library is the one we're after: 

https://stackoverflow.com/questions/20776205/point-in-polygon-with-geojson-in-python

**Comment by Mike-Heneghan** [comment]
Spatial Data: https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search;jsessionid=C2E7BCE5BCC10F4E43717825B3982CC5#/metadata/f12c3826-4b4b-40e6-bf4f-77b9ed01dc14

Geodecoder: https://mygeodata.cloud/converter/wfs-to-geojson

**Comment by Mike-Heneghan** [comment]
Objective:

Objective is an array of boundary data matches:

`[{'code-type':'local_authority', 'code':'S12000046', 'name': 'Glasgow City' }, {{'code-type':'health_board', 'code':'S08000021', 'name': 'Glasgow Area } ]`

**Comment by Mike-Heneghan** [comment]
Geo Data for Scottish Loca Authorities:

- https://github.com/martinjc/UK-GeoJSON/tree/master/json/administrative/sco

**Comment by Mike-Heneghan** [comment]
The ultimate goal of the feature is:

- To create a search which can match boundaries providing taking a (lat,lng) as arguments. 
- To create a way of checking how many services are in a boundary.

**Comment by Mike-Heneghan** [comment]
Need to move the geocoder code into `search.py` and add tests to ensure it's working correctly.

**Comment by Mike-Heneghan** [comment]
To do:

- [ ] Find more boundary geo data to test against.
- [ ] Update the boundary check to use the extra data sets.
- [ ] Find a way to process the keys dependent on the data set?

**Comment by Mike-Heneghan** [comment]
Required methods:

- A method which takes a `data_set`, `data_set_keys`, and `lat-long`) and returns match objects i.e. `{'code-type':'local_authority', 'code':'S12000046', 'name': 'Glasgow City' }`.

**Comment by Mike-Heneghan** [comment]
After trying to download the WFS data without success instead downloaded EsriShape data and uploaded it to https://mapshaper.org/ then exported as geojson.

**Comment by Mike-Heneghan** [comment]
Download QGIS and try to process the Health Board boundary data and convert into the correct format.

**Comment by Mike-Heneghan** [comment]
Health Integration Authorities:

https://spatialdata.gov.scot/geonetwork/srv/eng/catalog.search;jsessionid=B56BC78E7E3D46F6847E18A7AF298975#/metadata/ac5e870f-8fc2-4c21-8b9c-3bd2311a583f

**Comment by Mike-Heneghan** [comment]
Now a long_lat can be passed in as an argument to `check_boundaries` and an object of all matching boundaries is returned.

**Comment by Mike-Heneghan** [comment]
Refactor the boundary_mappings as dictionaries and remove the unnecessary repetition of `long_lat`

**Comment by Mike-Heneghan** [comment]
Merge into master
