### ISSUE TITLE
Create content block model and views for managing.

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#81]
I checked out CMS options, and they all seem overkill for our needs right now. All we need is a way to insert some custom html on v. few pages. 

Could be achieved by a new `ContentBlock` model: 

- default uuid identifier
- slug: for identifying / retrieving content blocks
- body: for html to be used

Plus, views to manage "content blocks" from the django admin. 

Content via blocks can then be inserted into templates via a templatetag that given a slug param will retrieve and insert the html in body. If not retrieve templatetag returns false.

Integrate with the place/category page, if block show, if not, show default blurb.

**Comment by digitalWestie** [comment]
path: /places/glasgow

`{% content_render path %}`

slugified_path  slugified 'places-glasgow'

`ContentBlock.objects.get(slug='places-glasgow')`

`{% content_render slugified_path %}`

`{% content_render 'my-other-block-slug' %}`

`{%  content_render path as content_result %}`

`{% if content_result %} {{ content_result }}` 
block_render
`{% content_render path + "-2" %}`

**Comment by Mike-Heneghan** [comment]
To do:

- [ ] Create new `ContentBlock` model.
- [ ] Add an admin view to allow the content to be added.
- [ ] Add the templatetag for displaying the `ContentBlock` instances.

**Comment by Mike-Heneghan** [comment]
Merged into master
