### ISSUE TITLE
Error parsing geojson feature response

### ISSUE THREAD

**Issue by digitalWestie** [Mike-Heneghan/ALISS#87]
See console / network response for - http://staging-aliss.herokuapp.com/services/lets-talk-0/

It looks like one of the geojson features in the response is being returned as a string.

**Comment by Mike-Heneghan** [comment]
Looks like there are two problems:

1. The service area features are not being found in the data.
2. When a feature is not found then none are rendered. 

From http://staging-aliss.herokuapp.com/api/v4/service-area-spatial/?service_id=d6b90c64-da5b-49a3-b347-7dee35011b4b found the missing features were:

- Tayside
- Fife 
- Perth and Kinross

Checked the data and found the service area codes don't match between the 2019 HB and HIA geojson and the ServiceArea model DB data respectively i.e.

- Fife (Health board):
  - GeoJSON: S08000029
  - DB: S08000018

- Tayside (Health board):
  - GeoJSON: S08000030
  - DB: S08000027

- Perth & Kinross (Health Integration Authority):
  - GeoJSON: S37000033
  - DB: S37000023

- [ ] May need to update the DB data to match the presumably newer GeoJSON data.
- [ ] Need to improve robustness if the code to handle invalid ServiceArea codes.

**Comment by Mike-Heneghan** [comment]
Merged into master
